[0m11:14:00.283154 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002092F914FD0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002092FB4F850>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002092F915390>]}


============================== 11:14:00.291223 | 0f20ef14-0d71-406f-9b70-16b25271bd77 ==============================
[0m11:14:00.291223 [info ] [MainThread]: Running with dbt=1.10.0-b2
[0m11:14:00.295239 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'debug': 'False', 'version_check': 'True', 'log_path': 'logs', 'profiles_dir': 'C:\\Users\\franc\\.dbt', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'static_parser': 'True', 'invocation_command': 'dbt init semrushpayments', 'introspect': 'True', 'target_path': 'None', 'log_format': 'default', 'send_anonymous_usage_stats': 'True'}
[0m11:14:00.385885 [debug] [MainThread]: Starter project path: C:\Users\franc\AppData\Local\Programs\Python\Python311\Lib\site-packages\dbt\include\starter_project
[0m11:14:00.398314 [info ] [MainThread]: 
Your new dbt project "semrushpayments" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m11:14:00.398314 [info ] [MainThread]: Setting up your profile.
[0m11:14:08.981544 [debug] [MainThread]: Command `dbt init` succeeded at 11:14:08.981544 after 8.79 seconds
[0m11:14:08.981544 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000209290998D0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002092F811690>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002092FB01C50>]}
[0m11:14:08.981544 [debug] [MainThread]: Flushing usage events
[0m11:14:20.482015 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m15:16:12.093104 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000025126AEF310>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002512273D050>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000025126AF5A90>]}


============================== 15:16:12.097527 | 435d96c0-d935-4a54-9e3b-edd0a95f6861 ==============================
[0m15:16:12.097527 [info ] [MainThread]: Running with dbt=1.10.0-b2
[0m15:16:12.097527 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\franc\\.dbt', 'fail_fast': 'False', 'debug': 'False', 'log_path': 'logs', 'warn_error': 'None', 'version_check': 'True', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'False', 'log_format': 'default', 'static_parser': 'True', 'invocation_command': 'dbt run', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'target_path': 'None', 'introspect': 'True', 'send_anonymous_usage_stats': 'True'}
[0m15:16:12.097527 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Users\franc\OneDrive\Escritorio\Semrush\semrush-datamodel\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m15:16:12.097527 [debug] [MainThread]: Command `dbt run` failed at 15:16:12.097527 after 0.11 seconds
[0m15:16:12.097527 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000025126A85F10>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000025126AF7DD0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000025126AF4810>]}
[0m15:16:12.102610 [debug] [MainThread]: Flushing usage events
[0m15:16:12.612019 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m17:12:02.551375 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001CF56AC06D0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001CF56A7C310>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001CF56AC0F10>]}


============================== 17:12:02.555375 | bfe52892-4033-4a41-ac31-b7a94738a909 ==============================
[0m17:12:02.555375 [info ] [MainThread]: Running with dbt=1.10.0-b2
[0m17:12:02.556157 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\franc\\.dbt', 'debug': 'False', 'version_check': 'True', 'log_path': 'logs', 'warn_error': 'None', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'False', 'log_format': 'default', 'invocation_command': 'dbt build', 'static_parser': 'True', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'target_path': 'None', 'introspect': 'True', 'send_anonymous_usage_stats': 'True'}
[0m17:12:02.556157 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Users\franc\OneDrive\Escritorio\Semrush\semrush-datamodel\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m17:12:02.558266 [debug] [MainThread]: Command `dbt build` failed at 17:12:02.557293 after 0.12 seconds
[0m17:12:02.558266 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001CF56A71E50>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001CF568898D0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001CF56AE0FD0>]}
[0m17:12:02.559223 [debug] [MainThread]: Flushing usage events
[0m17:12:03.038659 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m17:36:18.074717 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001E39E991FD0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001E39DCC8850>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001E39E68E990>]}


============================== 17:36:18.077731 | 8edc1ae3-9093-491f-a256-6a33e4bb1eff ==============================
[0m17:36:18.077731 [info ] [MainThread]: Running with dbt=1.10.0-b2
[0m17:36:18.078732 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\franc\\.dbt', 'fail_fast': 'False', 'version_check': 'True', 'log_path': 'logs', 'debug': 'False', 'warn_error': 'None', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'log_format': 'default', 'invocation_command': 'dbt docs generate', 'static_parser': 'True', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'target_path': 'None', 'introspect': 'True', 'send_anonymous_usage_stats': 'True'}
[0m17:36:18.079716 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Users\franc\OneDrive\Escritorio\Semrush\semrush-datamodel\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m17:36:18.080716 [debug] [MainThread]: Command `dbt docs generate` failed at 17:36:18.080716 after 0.09 seconds
[0m17:36:18.080716 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001E39E990590>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001E39E993E50>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001E39E992D50>]}
[0m17:36:18.082219 [debug] [MainThread]: Flushing usage events
[0m17:36:18.618139 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m18:12:34.711058 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001D8F3F0CF10>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001D8F4141E90>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001D8F4141910>]}


============================== 18:12:34.711058 | 406d3477-b827-430f-a3c5-c6dafc7e51ac ==============================
[0m18:12:34.711058 [info ] [MainThread]: Running with dbt=1.10.0-b2
[0m18:12:34.721203 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'version_check': 'True', 'profiles_dir': 'C:\\Users\\franc\\.dbt', 'log_path': 'logs', 'debug': 'False', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'False', 'log_format': 'default', 'static_parser': 'True', 'invocation_command': 'dbt build', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'target_path': 'None', 'introspect': 'True', 'send_anonymous_usage_stats': 'True'}
[0m18:12:34.721203 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Users\franc\OneDrive\Escritorio\Semrush\semrush-datamodel\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m18:12:34.721203 [debug] [MainThread]: Command `dbt build` failed at 18:12:34.721203 after 0.11 seconds
[0m18:12:34.721203 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001D8F4162D90>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001D8F40F6050>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001D8ED6EAF50>]}
[0m18:12:34.721203 [debug] [MainThread]: Flushing usage events
[0m18:12:35.228714 [debug] [MainThread]: An error was encountered while trying to flush usage events
